[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "https://www.websitework4less.com/*"
  to = "https://websitework4less.com/:splat"
  status = 301
  force = true
